name: Python Package Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install poetry
        poetry install
    - name: Run flake8 & black
      run: |
        poetry run flake8 . --count --show-source --statistics
        poetry run black --check --diff --skip-string-normalization .
    - name: Run pytest with coverage
      run: |
        poetry run coverage run -m pytest -v .
        poetry run coverage report -m